language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - os: osx
script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
notifications:
  email:
    on_success: never
